development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: feedback_system_development
  pool: 5
  username: root
  password: q
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: feedback_system_test
  pool: 5
  username: root
  password: q
  socket: /var/run/mysqld/mysqld.sock

production:
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode