Rails.application.routes.draw do
	root to: "persons#home"
	get "/home" , to: "persons#home"
	get "/contact" , to: "home#contact"
	get "/about" , to: "home#about"
	post "/login", to: "persons#login"
	get "/staff/:id",to: "staff#home"
	get "/students/:id",to: "students#home"
	get "/logout" , to: "persons#logout"
	get "students/:id/feedback/:course_id" , to: "students#feedback"
	get "staff/:id/feedback/:course_id" , to: "staff#feedback"
	get "staff/:id/comments/:course_id" , to: "staff#comments"
	post "/feedbackinsert", to: "students#feedback_insert"
	get "staff/:id/statistics/:course_id" , to: "staff#statistics"
end
